### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Janestar33** [DeeCeeXxx/Queen_Anita-V2#115]
A bug should be added and uploaded to Anita v2

Venom2 should have a good normal bot menu
Stuff like setsudo and share should be added 
Thanks bro

**Comment by anonphoenix007** [comment]
You need to understand how bot works before you can ask for a specific function ,I have personally tried to add setsudo commands in A case bot like Venom before but it's of no use because there are commands for it already like the addowner and addprem command .

For the bugs in Queen_Anita-V2 ,We are currently working on that and they will be available in the future ,we ask for your patience dear Queen_Anita-V2 user.
